### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by fromage9747** [DevJaGz/app-fast-marquee#2]
Recently discovered that each instance of ngx-fast-marquee can consume up to 20% of the CPU in the browser.

I have a Babylonjs scene and two marquee instances overlayed.  This 40% cpu usage causes the FPS of my Babylonjs scene to drop to near 20FPS.

Of course, I can just not use your repo but thought I would let you know.

It's a great repo and works the best from various implementations I have tried, but I wonder if there is a way to limit the amount of function calls so that Angular is not chewing through the CPU cycles unnecessarily.

**Comment by DevJaGz** [comment]
Hi @fromage9747, thanks for your message! The marquee updates under the following conditions:

- When the marquee is resized.
- When any text within the marquee's child elements changes.
- When the number of child elements in the marquee changes.

I suggest validating whether your code is triggering these conditions. If the issue persists, feel free to provide more details, and I'll be happy to assist further.

**Comment by fromage9747** [comment]
@DevJaGz 

Hey man, thanks for the reply.  I went and console logged all the methods in the ts file and pretty much they are just continuously running. 

I'm not doing anything weird with your repo, just installed and added it. 

I spent the afternoon creating a pure CSS implementation which has suited my needs. Pretty much exactly the same as what yours produces with almost nothing on the CPU. 

Cheers!

**Comment by DevJaGz** [comment]
Hi @fromage9747, thanks for the update! Glad to hear you found a solution that works well for your needs. A pure CSS implementation is a great approach, especially for reducing CPU usage.

If you ever want to revisit using the library or need any further help, feel free to reach out. Cheers, and best of luck with your project!
